
[dev]
13.82.179.230

---

- hosts: all
  gather_facts: False
  connection: local

  tasks:

    - name: ping
      shell: ping -c 1 -w 2 8.8.8.8
      ignore_errors: true
---
- hosts: dev
  become: true
  tasks:
    - yum:
        name:
          - httpd
        state: present
    - service: name=httpd state=started enabled=yes
    - raw: "echo Welcome to AzureDevops | sudo tee /var/www/html/index.html"
---
- hosts: qa
  tasks:
    - name: Execute Shell Commands
      shell: uname
      register: uname_result
    - debug: msg="{{ uname_result.stdout }}"
---
- hosts: qa
  tasks:
    - name: Kernel
      debug: msg="{{ ansible_kernel }}"
    - name: Hostname
      debug: msg="{{ ansible_hostname }}"
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - debug: var=ansible_architecture
    - debug: var=inventory_hostname
    - debug: var=groups
    - debug: var=group_names
    - debug: var=hostvars    
    
